# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/autolinker/prism-autolinker.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/autoloader/prism-autoloader.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/command-line/prism-command-line.min.css
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/command-line/prism-command-line.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/copy-to-clipboard/prism-copy-to-clipboard.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/custom-class/prism-custom-class.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/data-uri-highlight/prism-data-uri-highlight.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/diff-highlight/prism-diff-highlight.min.css
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/diff-highlight/prism-diff-highlight.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/download-button/prism-download-button.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/file-highlight/prism-file-highlight.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/filter-highlight-all/prism-filter-highlight-all.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/highlight-keywords/prism-highlight-keywords.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/inline-color/prism-inline-color.min.css
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/inline-color/prism-inline-color.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/jsonp-highlight/prism-jsonp-highlight.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/keep-markup/prism-keep-markup.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/line-highlight/prism-line-highlight.min.css
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/line-highlight/prism-line-highlight.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/line-numbers/prism-line-numbers.min.css
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/line-numbers/prism-line-numbers.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/match-braces/prism-match-braces.min.css
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/match-braces/prism-match-braces.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/normalize-whitespace/prism-normalize-whitespace.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/previewers/prism-previewers.min.css
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/previewers/prism-previewers.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/remove-initial-line-feed/prism-remove-initial-line-feed.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/show-invisibles/prism-show-invisibles.min.css
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/show-invisibles/prism-show-invisibles.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/show-language/prism-show-language.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/toolbar/prism-toolbar.min.css
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/toolbar/prism-toolbar.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/treeview/prism-treeview.min.css
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/treeview/prism-treeview.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/unescaped-markup/prism-unescaped-markup.min.css
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/unescaped-markup/prism-unescaped-markup.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/wpd/prism-wpd.min.css
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/wpd/prism-wpd.min.js

curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/themes/prism-dark.min.css
curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/themes/prism-funky.min.css
curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/themes/prism-okaidia.min.css
curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/themes/prism-solarizedlight.min.css
curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/themes/prism-tomorrow.min.css
curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/themes/prism-twilight.min.css
curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/themes/prism.min.css

# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-abap.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-abnf.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-actionscript.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-ada.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-agda.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-al.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-antlr4.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-apacheconf.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-apex.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-apl.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-applescript.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-aql.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-arduino.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-arff.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-asciidoc.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-asm6502.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-aspnet.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-autohotkey.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-autoit.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-bash.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-basic.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-batch.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-bbcode.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-birb.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-bison.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-bnf.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-brainfuck.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-brightscript.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-bro.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-bsl.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-c.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-cfscript.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-chaiscript.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-cil.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-clike.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-clojure.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-cmake.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-cobol.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-coffeescript.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-concurnas.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-coq.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-core.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-cpp.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-crystal.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-csharp.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-csp.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-css-extras.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-css.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-csv.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-cypher.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-d.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-dart.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-dataweave.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-dax.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-dhall.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-diff.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-django.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-dns-zone-file.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-docker.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-dot.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-ebnf.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-editorconfig.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-eiffel.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-ejs.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-elixir.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-elm.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-erb.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-erlang.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-etlua.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-excel-formula.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-factor.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-false.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-firestore-security-rules.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-flow.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-fortran.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-fsharp.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-ftl.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-gcode.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-gdscript.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-gedcom.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-gherkin.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-git.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-glsl.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-gml.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-go.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-graphql.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-groovy.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-haml.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-handlebars.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-haskell.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-haxe.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-hcl.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-hlsl.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-hpkp.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-hsts.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-http.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-ichigojam.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-icon.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-icu-message-format.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-idris.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-iecst.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-ignore.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-inform7.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-ini.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-io.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-j.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-java.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-javadoc.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-javadoclike.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-javascript.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-javastacktrace.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-jexl.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-jolie.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-jq.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-js-extras.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-js-templates.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-jsdoc.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-json.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-json5.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-jsonp.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-jsstacktrace.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-jsx.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-julia.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-keyman.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-kotlin.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-kumir.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-latex.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-latte.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-less.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-lilypond.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-liquid.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-lisp.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-livescript.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-llvm.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-log.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-lolcode.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-lua.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-makefile.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-markdown.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-markup-templating.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-markup.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-matlab.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-mel.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-mizar.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-mongodb.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-monkey.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-moonscript.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-n1ql.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-n4js.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-nand2tetris-hdl.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-naniscript.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-nasm.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-neon.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-nevod.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-nginx.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-nim.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-nix.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-nsis.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-objectivec.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-ocaml.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-opencl.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-openqasm.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-oz.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-parigp.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-parser.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-pascal.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-pascaligo.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-pcaxis.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-peoplecode.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-perl.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-php-extras.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-php.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-phpdoc.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-plsql.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-powerquery.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-powershell.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-processing.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-prolog.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-promql.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-properties.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-protobuf.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-psl.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-pug.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-puppet.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-pure.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-purebasic.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-purescript.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-python.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-q.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-qml.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-qore.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-qsharp.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-r.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-racket.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-reason.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-regex.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-rego.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-renpy.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-rest.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-rip.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-roboconf.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-robotframework.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-ruby.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-rust.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-sas.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-sass.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-scala.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-scheme.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-scss.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-shell-session.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-smali.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-smalltalk.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-smarty.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-sml.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-solidity.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-solution-file.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-soy.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-sparql.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-splunk-spl.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-sqf.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-sql.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-squirrel.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-stan.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-stylus.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-swift.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-t4-cs.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-t4-templating.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-t4-vb.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-tap.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-tcl.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-textile.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-toml.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-tsx.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-tt2.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-turtle.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-twig.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-typescript.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-typoscript.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-unrealscript.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-uri.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-v.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-vala.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-vbnet.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-velocity.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-verilog.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-vhdl.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-vim.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-visual-basic.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-warpscript.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-wasm.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-wiki.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-wolfram.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-xeora.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-xml-doc.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-xojo.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-xquery.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-yaml.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-yang.min.js
# curl -LO https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-zig.min.js
